In [324]:
# Data from : https://www.espncricinfo.com/records/highest-career-batting-average-282910

In [325]:
# import lib

In [326]:
import pandas as pd

In [327]:
# import csv

In [328]:
df = pd.read_csv('./data/CricketTestMatchData.csv')
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),19281948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7.0,626+,6
1,PHKD Mendis (SL),20222025,12,21,2,1184,182*,62.31,1839,64.38,5,4,NaN,123,23
2,AC Voges (AUS),20152016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2.0,186,5
3,RG Pollock (SA),19631970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1.0,246+,11
4,GA Headley (WI),19301954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2.0,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,WH Ponsford (AUS),19241934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1.0,119+,0
62,SJ McCabe (AUS),19301938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4.0,241+,5+
63,DR Jardine (ENG),19281934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2.0,53+,0
64,KC Bland (SA),19611966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2.0,123+,20
65,AB de Villiers (SA),20042018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8.0,1024,64

In [329]:
df['Span'] = df['Span'].astype(str)
df['Span'] = df['Span'].str.replace(r'(\d{4})(\d{4})', r'\1-\2', regex=True)

In [330]:
# rename multiple column

In [331]:
df = df.rename(columns = {'Player':'Player_Name', 'Span':'Playing_span',	'Mat':'matches_played', 'Inns':'Innings_batted', 'NO':'Not_outs', 
                          'Runs':'Runs_scored','HS' : 'Highest_inns_score',	'Ave':'Batting_average', 'BF':'Balls_faced', 'SR':'Batting_strike_rate', 
                          '100' : 'Hundreds_scored', '50':'Fifties_scored',	'0':'Ducks_scored',	'4s':'Boundary_fours',	'6s':'Boundary_sixes'})

In [332]:
df.head()

,Player_Name,Playing_span,matches_played,Innings_batted,Not_outs,Runs_scored,Highest_inns_score,Batting_average,Balls_faced,Batting_strike_rate,Hundreds_scored,Fifties_scored,Ducks_scored,Boundary_fours,Boundary_sixes
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7.0,626+,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,NaN,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2.0,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1.0,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2.0,104+,1

In [333]:
# check null value

In [334]:
df.isna().any()

Player_Name            False
Playing_span           False
matches_played         False
Innings_batted         False
Not_outs               False
Runs_scored            False
Highest_inns_score     False
Batting_average        False
Balls_faced             True
Batting_strike_rate    False
Hundreds_scored        False
Fifties_scored         False
Ducks_scored            True
Boundary_fours         False
Boundary_sixes         False
dtype: bool

In [335]:
df.isna().sum()

Player_Name            0
Playing_span           0
matches_played         0
Innings_batted         0
Not_outs               0
Runs_scored            0
Highest_inns_score     0
Batting_average        0
Balls_faced            3
Batting_strike_rate    0
Hundreds_scored        0
Fifties_scored         0
Ducks_scored           1
Boundary_fours         0
Boundary_sixes         0
dtype: int64

In [336]:
df[df['Balls_faced'].isna()==1]

,Player_Name,Playing_span,matches_played,Innings_batted,Not_outs,Runs_scored,Highest_inns_score,Batting_average,Balls_faced,Batting_strike_rate,Hundreds_scored,Fifties_scored,Ducks_scored,Boundary_fours,Boundary_sixes
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,0.0,15,19,6.0,258+,2
16,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,0.0,15,14,1.0,107+,11
56,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,NaN,0.0,5,6,3.0,51+,0

In [337]:
df['Balls_faced'] = df['Balls_faced'].fillna(0)

In [338]:
df['Ducks_scored'] = df['Ducks_scored'].fillna(0)

In [339]:
#drop duplicates

In [340]:
df.duplicated().any()

True

In [341]:
df.duplicated().sum()

4

In [342]:
df[df['Player_Name'].duplicated() == 1]

,Player_Name,Playing_span,matches_played,Innings_batted,Not_outs,Runs_scored,Highest_inns_score,Batting_average,Balls_faced,Batting_strike_rate,Hundreds_scored,Fifties_scored,Ducks_scored,Boundary_fours,Boundary_sixes
9,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2.0,202+,6
51,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12.0,908+,26
64,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2.0,123+,20
65,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8.0,1024,64

In [343]:
df[df['Player_Name'].isin(['H Sutcliffe (ENG)','SM Gavaskar (IND)','KC Bland (SA)','AB de Villiers (SA)'])]

,Player_Name,Playing_span,matches_played,Innings_batted,Not_outs,Runs_scored,Highest_inns_score,Batting_average,Balls_faced,Batting_strike_rate,Hundreds_scored,Fifties_scored,Ducks_scored,Boundary_fours,Boundary_sixes
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2.0,202+,6
9,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2.0,202+,6
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12.0,908+,26
41,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8.0,1024,64
51,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12.0,908+,26
54,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2.0,123+,20
64,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2.0,123+,20
65,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8.0,1024,64

In [344]:
df = df.drop_duplicates()

In [345]:
df.duplicated().any()

False

In [346]:
# spliting Playing_span to start and end date + carer length

In [347]:
df['Playing_span'].str.split('-')

0     [1928, 1948]
1     [2022, 2025]
2     [2015, 2016]
3     [1963, 1970]
4     [1930, 1954]
          ...
59    [1965, 1981]
60    [2002, 2014]
61    [1924, 1934]
62    [1930, 1938]
63    [1928, 1934]
Name: Playing_span, Length: 62, dtype: object

In [348]:
df['Starting_year'] = df['Playing_span'].str.split('-').str[0]
df['Final_year'] = df['Playing_span'].str.split('-').str[1]

In [349]:
df.head()

,Player_Name,Playing_span,matches_played,Innings_batted,Not_outs,Runs_scored,Highest_inns_score,Batting_average,Balls_faced,Batting_strike_rate,Hundreds_scored,Fifties_scored,Ducks_scored,Boundary_fours,Boundary_sixes,Starting_year,Final_year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7.0,626+,6,1928,1948
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,0.0,123,23,2022,2025
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2.0,186,5,2015,2016
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1.0,246+,11,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2.0,104+,1,1930,1954

In [350]:
#droping Playing_span column

In [351]:
df.drop('Playing_span', axis = 1,inplace = True)
# df.drop(['Playing_span'], axis = 1,inplace = True)     # to drop multiple column use [] 

# cann use inplace = true / df = df.drop()   both will save the change

In [352]:
df.head()

,Player_Name,matches_played,Innings_batted,Not_outs,Runs_scored,Highest_inns_score,Batting_average,Balls_faced,Batting_strike_rate,Hundreds_scored,Fifties_scored,Ducks_scored,Boundary_fours,Boundary_sixes,Starting_year,Final_year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7.0,626+,6,1928,1948
1,PHKD Mendis (SL),12,21,2,1184,182*,62.31,1839,64.38,5,4,0.0,123,23,2022,2025
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2.0,186,5,2015,2016
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1.0,246+,11,1963,1970
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2.0,104+,1,1930,1954

In [353]:
# Extract the country code and save it in a new column
df['Country'] = df['Player_Name'].str.extract(r'\((\w+)\)')

# Remove the country code from the original column
df['Player_Name'] = df['Player_Name'].str.replace(r'\s*\(\w+\)', '', regex=True)

In [354]:
df.sample(3)

,Player_Name,matches_played,Innings_batted,Not_outs,Runs_scored,Highest_inns_score,Batting_average,Balls_faced,Batting_strike_rate,Hundreds_scored,Fifties_scored,Ducks_scored,Boundary_fours,Boundary_sixes,Starting_year,Final_year,Country
40,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14.0,1049,82,1994,2009,AUS
37,SM Gavaskar,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12.0,908+,26,1971,1987,IND
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1.0,246+,11,1963,1970,SA

In [355]:
# # other method
# # country
# df['Player_Name'].str.split('(')
# df['Country'] = df['Player_Name'].str.split('(').str[1]
# df['Country'] = df['Country'].str.split(')').str[0]

# # player name
# df['Player_Name'] = df['Player_Name'].str.split('(').str[0]

In [356]:
# change data types

In [357]:
df.dtypes

Player_Name             object
matches_played           int64
Innings_batted           int64
Not_outs                 int64
Runs_scored              int64
Highest_inns_score      object
Batting_average        float64
Balls_faced             object
Batting_strike_rate    float64
Hundreds_scored          int64
Fifties_scored           int64
Ducks_scored           float64
Boundary_fours          object
Boundary_sixes          object
Starting_year           object
Final_year              object
Country                 object
dtype: object

In [358]:
df['Highest_inns_score'] = df['Highest_inns_score'].str.split('*').str[0]
df['Highest_inns_score'] = df['Highest_inns_score'].astype(int)

In [359]:
# df['Balls_faced'] = df['Balls_faced'].astype('int')
# df['Boundary_fours'] = df['Boundary_fours'].astype('int')
# df['Boundary_sixes'] = df['Boundary_sixes'].astype('int')

In [360]:
df['Boundary_fours'] = df['Boundary_fours'].str.split('+').str[0]
df['Boundary_sixes'] = df['Boundary_sixes'].str.split('+').str[0]

In [361]:
df = df.astype({'Boundary_fours':'int', 'Boundary_sixes' : 'int', 'Starting_year':'int', 'Final_year':'int'})

In [401]:
df.dtypes

Player_Name             object
matches_played           int64
Innings_batted           int64
Not_outs                 int64
Runs_scored              int64
Highest_inns_score       int32
Batting_average        float64
Balls_faced             object
Batting_strike_rate    float64
Hundreds_scored          int64
Fifties_scored           int64
Ducks_scored           float64
Boundary_fours           int32
Boundary_sixes           int32
Starting_year            int32
Final_year               int32
Country                 object
dtype: object

In [403]:
df['Career_length'] = df['Final_year'] - df['Starting_year']

In [405]:
df.head()

,Player_Name,matches_played,Innings_batted,Not_outs,Runs_scored,Highest_inns_score,Batting_average,Balls_faced,Batting_strike_rate,Hundreds_scored,Fifties_scored,Ducks_scored,Boundary_fours,Boundary_sixes,Starting_year,Final_year,Country,Career_length
0,DG Bradman,52,80,10,6996,334,99.94,9800+,58.60,29,13,7.0,626,6,1928,1948,AUS,20
1,PHKD Mendis,12,21,2,1184,182,62.31,1839,64.38,5,4,0.0,123,23,2022,2025,SL,3
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2.0,186,5,2015,2016,AUS,1
3,RG Pollock,23,41,4,2256,274,60.97,1707+,54.48,7,11,1.0,246,11,1963,1970,SA,7
4,GA Headley,22,40,4,2190,270,60.83,416+,56.00,10,5,2.0,104,1,1930,1954,WI,24

In [407]:
# Q1 : Avg career length

In [415]:
df['Career_length'].mean()

12.96774193548387

In [409]:
# Q2 : avg strike rate for player with 10+ years exp

In [417]:
df[df['Career_length'] > 10 ]['Batting_strike_rate'].mean()

47.80186046511628

In [411]:
# q3 : no of cricketers plyed before 1960

In [423]:
df[df['Starting_year'] < 1960]['Player_Name'].count()

23

In [413]:
# q4 : max high inn score by a coutry

In [425]:
df.groupby('Country')['Highest_inns_score'].max()

Country
AUS    380
ENG    364
IND    248
NZ     251
PAK    313
SA     278
SL     374
WI     365
ZIM    232
Name: Highest_inns_score, dtype: int32

In [ ]:
# q5 : hundreds, fifties, ducks AVG by country

In [429]:
df.groupby('Country')[['Hundreds_scored', 'Fifties_scored', 'Ducks_scored' ]].mean()

         Hundreds_scored  Fifties_scored  Ducks_scored
Country
AUS            21.533333       28.933333      8.933333
ENG            13.076923       21.384615      4.461538
IND            23.250000       31.500000      8.000000
NZ             33.000000       37.000000     11.000000
PAK            17.800000       24.200000      8.000000
SA              9.800000       20.200000      3.400000
SL             22.750000       34.000000      9.250000
WI             16.625000       25.625000      7.250000
ZIM            12.000000       27.000000      5.000000